### ISSUE TITLE
Manager failed to start - Syntax errors in values.py

### ISSUE THREAD

**Issue by brittonx** [ShaneSmiskol/openpilot#182]
I came out to the car today and found this error.  It comes back on every reboot.
![20200826_115849](https://user-images.githubusercontent.com/60303682/91333420-92610380-e79b-11ea-86b0-156e67da8ec8.jpg)

I edited the file, there was a missing comma at the end of the line before that.

Then, on reboot, I got the following error:
![20200826_125007](https://user-images.githubusercontent.com/60303682/91333593-c5a39280-e79b-11ea-8a8e-1d9fc3bdb6ef.jpg)

Not sure what is messing up the values.py

**Comment by brittonx** [comment]
I removed lines 143-153 on my C2 then it was able to boot.

**Comment by brittonx** [comment]
I think a problem is if this gets hosed, I don't thing the updater is able to update the file with a revised version where you may have already corrected the issue.  You may want to have a "stock_additions_staging" where you can test that updates don't prevent the unit from booting before the updates get pushed out to those of us who are running this fork.  This is the second time this has happened.  The first time, I just did a reinstall which is a pain.

**Comment by ShaneSmiskol** [comment]
Hey @brittonx, this issue was fixed about an hour after the bad PR was merged, but if your C2 was on when the bad commit went through it pulled that and stopped manager from updating itself to get the latest fixing commit. You're right about the updater, if manager doesn't start it can't get updates.

I'll add a git pull line in the openpilot_launcher file so it can get new updates on boot up if there's an error, that will be before openpilot even starts up.

Sorry about this, I failed to check that a PR had correct syntax before merging a new fingerprint. If you can ssh in all you need to do is `git pull` and it should be fixed now. Make sure to `git reset --hard origin/stock_additions` if you changed stuff locally so git pull will go through

**Comment by brittonx** [comment]
Thank you for the update. I'm okay if you want to close this issue.

**Comment by ShaneSmiskol** [comment]
Merged into SA, if this ever happens again ensure your device is on WiFi and tap the new Reset button to perform a git pull and reset --hard!
